# Trabajo final

## Cargar librerías

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Importar data

In [4]:
df = pd.read_excel("dataset_trabajo_final.xlsx")
df

,Institución,Departamento,Nombre,Apellido(s),Dirección de correo,Ciudad,Nombre de usuario,Género,RUT,Institución por Región,Examen Final (Real),Total C_examen (Real),Test Módulo 1 (Real),Test Módulo 2 (Real),Test Módulo 3 (Real),Test Módulo 4 (Real),Total del curso (Real),Última descarga del curso
0,Escuela Nacional de Ingeniería,Ciencias de la Computación,Juana,Garmendia Gomila,jgarmendia@hotmail.com,La Serena,jgarmendia,Masculino,8017069,REGIÓN METROPOLITANA,74,96,-,84,-,-,84.67,1633466531
1,Escuela Nacional de Ingeniería,Salud Comunitaria,Adelia,Ruiz Arenas,aruiz@gmail.com,Antofagasta,aruiz,Femenino,21.063.126-5,Región Metropolitana,77,100,-,-,44,-,73.67,1681979156
2,Instituto Tecnológico Andino,Administración Pública,felisa,tirado viña,ftiradogmail.com,Concepción,ftirado,Masculino,108689517,Valparaíso,94,-,97,-,-,-,95.5,1648341847
3,Escuela Nacional de Ingeniería,Estudios Internacionales,ruben,olivé pelayo,rolivé@yahoo.com,Santiago,rolivé,Masculino,83.327.119,Los Lagos,76,-,65,90,53,79,72.6,1629619491
4,Escuela Nacional de Ingeniería,Ciencias de la Computación,Sancho,Acevedo Sedano,sacevedo@yahoo.com,La Serena,sacevedo,Masculino,22.363.355,Maule,88,41,100,83,-,72,76.8,1619622462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Universidad del Pacífico,Estudios Internacionales,MARIANA,Valverde Bru,mvalverde,Santiago,mvalverde,Femenino,10.438.826-0,ARAUCANÍA,-,-,79,-,85,-,82,1675473220
131,Centro de Estudios Patagónicos,Educación y Pedagogía,JUAN,Jerez Cañellas,jjerez@gmail.com,Antofagasta,jjerez,Femenino,24507554-5,Valparaíso,-,89,-,40,-,-,64.5,1607226023
132,Escuela Nacional de Ingeniería,Ciencias de la Computación,lucho,báez llorente,lbáez@@yahoo.com,La Serena,lbáez,Masculino,139925222,Araucanía,-,-,-,-,81,-,81,1617153755
133,Academia Chilena de Ciencias Sociales,Educación y Pedagogía,Adolfo,Garcia Codina,agarcia@gmail.com,Santiago,agarcia,Femenino,218.537.216,Región Metropolitana,96,-,52,-,-,-,74,1658614458
134,Centro de Estudios Patagónicos,Administración Pública,Pili,Coloma Benet,pcoloma@gmail.com,Puerto Montt,pcoloma,Femenino,24.054.471-7,Los Lagos,-,-,59,-,-,-,59,1603077812

## Exploración inicial

In [5]:
print("Dimensiones del dataset")
print (df.size)
print (df.index)
print("-------------------------")

# TODO: Muestra los nombres de las columnas
print("Nombres de las columnas")
print (df.columns)
print("-------------------------")

# TODO: Revisa la información general del dataset
print("Información general del dataset")
df.info()
print("-------------------------")

Dimensiones del dataset
2430
RangeIndex(start=0, stop=135, step=1)
-------------------------
Nombres de las columnas
Index(['Institución', 'Departamento', 'Nombre', 'Apellido(s)',
       'Dirección de correo', 'Ciudad', 'Nombre de usuario', 'Género', 'RUT',
       'Institución por Región', 'Examen Final (Real)',
       'Total C_examen (Real)', 'Test Módulo 1 (Real)', 'Test Módulo 2 (Real)',
       'Test Módulo 3 (Real)', 'Test Módulo 4 (Real)',
       'Total del curso (Real)', 'Última descarga del curso'],
      dtype='object')
-------------------------
Información general del dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Institución                135 non-null    object
 1   Departamento               135 non-null    object
 2   Nombre                     135 non-null    object
 3   Apellido(s)                135 non-null    object
 4   Dirección de correo        135 non-null    object
 5   Ciudad                     135 non-null    object
 6   Nombre de usuario          135 non-null    object
 7   Género                     135 non-null    object
 8   RUT                        135 non-null    object
 9   Institución por Región     135 non-null    object
 10  Examen Final (Real)        135 non-null    object
 11  Total C_examen (Real)      135 non-null    object
 12  Test Módulo 1 (Real)       135 non-null    object
 13  Test Módulo 2 (Real)       135 non-null    object
 14  Test Módulo 3 (Real)       135 non-null    object
 15  Test Módulo 4 (Real)       135 non-null    object
 16  Total del curso (Real)     135 non-null    object
 17  Última descarga del curso  135 non-null    int64
dtypes: int64(1), object(17)
memory usage: 19.1+ KB
-------------------------

## Identificar si hay nulos

In [6]:
print(df.isnull().sum())

Institución                  0
Departamento                 0
Nombre                       0
Apellido(s)                  0
Dirección de correo          0
Ciudad                       0
Nombre de usuario            0
Género                       0
RUT                          0
Institución por Región       0
Examen Final (Real)          0
Total C_examen (Real)        0
Test Módulo 1 (Real)         0
Test Módulo 2 (Real)         0
Test Módulo 3 (Real)         0
Test Módulo 4 (Real)         0
Total del curso (Real)       0
Última descarga del curso    0
dtype: int64

## Revisión de duplicados

In [8]:
# Total de filas duplicadas (todas las columnas)
n_duplicados = df.duplicated().sum()
print(f"Filas completamente duplicadas: {n_duplicados}")

# Mostrar las filas duplicadas si existen
duplicados = df[df.duplicated(keep=False)]
if not duplicados.empty:
    print(f"\nRegistros duplicados ({len(duplicados)} filas):")
    display(duplicados)
else:
    print("No hay filas completamente duplicadas.")

# Revisar duplicados por columnas clave de identidad
cols_clave = ["RUT", "Nombre de usuario", "Dirección de correo"]
for col in cols_clave:
    dupes = df[df.duplicated(subset=[col], keep=False) & df[col].notna()]
    print(f"\nDuplicados por '{col}': {df.duplicated(subset=[col]).sum()}")
    if not dupes.empty:
        display(dupes[[col, "Nombre", "Apellido(s)", "Institución"]].sort_values(col, key=lambda x: x.astype(str)))

Filas completamente duplicadas: 15

Registros duplicados (30 filas):

,Institución,Departamento,Nombre,Apellido(s),Dirección de correo,Ciudad,Nombre de usuario,Género,RUT,Institución por Región,Examen Final (Real),Total C_examen (Real),Test Módulo 1 (Real),Test Módulo 2 (Real),Test Módulo 3 (Real),Test Módulo 4 (Real),Total del curso (Real),Última descarga del curso
5,Instituto Tecnológico Andino,Estudios Internacionales,feliciano,vallejo alemany,fvallejo@hotmail.com,La Serena,fvallejo,Masculino,22542550,Araucanía,-,-,-,-,-,-,-,1621803364
13,Centro de Estudios Patagónicos,Educación y Pedagogía,griselda,vilanova tello,gvilanova,Antofagasta,gvilanova,Femenino,17.508.442,RM,-,47,-,-,-,99,73,1674568419
22,Centro de Estudios Patagónicos,Administración Pública,Pili,Coloma Benet,pcoloma@gmail.com,Puerto Montt,pcoloma,Femenino,24.054.471-7,Los Lagos,-,-,59,-,-,-,59,1603077812
41,Escuela Nacional de Ingeniería,Ciencias de la Computación,lucho,báez llorente,lbáez@@yahoo.com,La Serena,lbáez,Masculino,139925222,Araucanía,-,-,-,-,81,-,81,1617153755
49,Instituto Tecnológico Andino,Administración Pública,Florencio,Losada Julián,flosada@yahoo.com,Valparaíso,flosada,Femenino,11.831.944-8,Valparaíso,-,-,-,-,-,49,49,1680115362
62,Centro de Estudios Patagónicos,Educación y Pedagogía,JUAN,Jerez Cañellas,jjerez@gmail.com,Antofagasta,jjerez,Femenino,24507554-5,Valparaíso,-,89,-,40,-,-,64.5,1607226023
74,Universidad del Pacífico,Estudios Internacionales,azahara,arana amat,aarana@gmail.com,Puerto Montt,aarana,Femenino,18.066.935-3,Los Lagos,50,-,41,-,90,-,60.33,1644674873
79,Centro de Estudios Patagónicos,Estudios Internacionales,Ernesto,Sabater Martorell,esabater@gmail.com,Coyhaique,esabater,Femenino,218785978,Valparaíso,89,-,82,87,-,55,78.25,1684567904
87,Centro de Estudios Patagónicos,Administración Pública,Remigio,Amorós Llopis,ramorós@gmail.com,La Serena,ramorós,Femenino,120427332,Biobío,-,-,40,-,94,61,65,1658029523
94,Academia Chilena de Ciencias Sociales,Educación y Pedagogía,Adolfo,Garcia Codina,agarcia@gmail.com,Santiago,agarcia,Femenino,218.537.216,Región Metropolitana,96,-,52,-,-,-,74,1658614458
97,Universidad del Pacífico,Ciencias de la Computación,CANDELARIA,Puga Nebot,cpuga@@yahoo.com,Antofagasta,cpuga,Masculino,205971883,Maule,44,-,-,-,-,57,50.5,1661958812
101,Centro de Estudios Patagónicos,Ciencias de la Computación,Amaya,Escribano Espada,aescribanogmail.com,Rancagua,aescribano,Masculino,12186570,Los Lagos,68,49,55,46,-,-,54.5,1692876430
105,Centro de Estudios Patagónicos,Arte y Patrimonio,melchor,alsina borja,malsina@yahoo.com,Rancagua,malsina,Femenino,13890179,Araucanía,46,-,-,68,-,-,57,1657345814
112,Universidad del Pacífico,Arte y Patrimonio,ASUNCIÓN,Julián Torrent,ajulián@gmail.com,Santiago,ajulián,Femenino,18.816.991-4,Maule,-,-,-,-,-,83,83,1639564411
113,Universidad del Pacífico,Estudios Internacionales,MARIANA,Valverde Bru,mvalverde,Santiago,mvalverde,Femenino,10.438.826-0,ARAUCANÍA,-,-,79,-,85,-,82,1675473220
120,Universidad del Pacífico,Arte y Patrimonio,ASUNCIÓN,Julián Torrent,ajulián@gmail.com,Santiago,ajulián,Femenino,18.816.991-4,Maule,-,-,-,-,-,83,83,1639564411
121,Universidad del Pacífico,Estudios Internacionales,azahara,arana amat,aarana@gmail.com,Puerto Montt,aarana,Femenino,18.066.935-3,Los Lagos,50,-,41,-,90,-,60.33,1644674873
122,Centro de Estudios Patagónicos,Estudios Internacionales,Ernesto,Sabater Martorell,esabater@gmail.com,Coyhaique,esabater,Femenino,218785978,Valparaíso,89,-,82,87,-,55,78.25,1684567904
123,Centro de Estudios Patagónicos,Administración Pública,Remigio,Amorós Llopis,ramorós@gmail.com,La Serena,ramorós,Femenino,120427332,Biobío,-,-,40,-,94,61,65,1658029523
124,Universidad del Pacífico,Ciencias de la Computación,CANDELARIA,Puga Nebot,cpuga@@yahoo.com,Antofagasta,cpuga,Masculino,205971883,Maule,44,-,-,-,-,57,50.5,1661958812
125,Centro de Estudios Patagónicos,Educación y Pedagogía,griselda,vilanova tello,gvilanova,Antofagasta,gvilanova,Femenino,17.508.442,RM,-,47,-,-,-,99,73,1674568419
126,Centro de Estudios Patagónicos,Ciencias de la Computación,Amaya,Escribano Espada,aescribanogmail.com,Rancagua,aescribano,Masculino,12186570,Los Lagos,68,49,55,46,-,-,54.5,1692876430
127,Instituto Tecnológico Andino,Estudios Internacionales,feliciano,vallejo alemany,fvallejo@hotmail.com,La Serena,fvallejo,Masculino,22542550,Araucanía,-,-,-,-,-,-,-,1621803364
128,Centro de Estudios Patagónicos,Arte y Patrimonio,melchor,alsina borja,malsina@yahoo.com,Rancagua,malsina,Femenino,13890179,Araucanía,46,-,-,68,-,-,57,1657345814
129,Instituto Tecnológico Andino,Administración Pública,Florencio,Losada Julián,flosada@yahoo.com,Valparaíso,flosada,Femenino,11.831.944-8,Valparaíso,-,-,-,-,-,49,49,1680115362
130,Universidad del Pacífico,Estudios Internacionales,MARIANA,Valverde Bru,mvalverde,Santiago,mvalverde,Femenino,10.438.826-0,ARAUCANÍA,-,-,79,-,85,-,82,1675473220
131,Centro de Estudios Patagónicos,Educación y Pedagogía,JUAN,Jerez Cañellas,jjerez@gmail.com,Antofagasta,jjerez,Femenino,24507554-5,Valparaíso,-,89,-,40,-,-,64.5,1607226023
132,Escuela Nacional de Ingeniería,Ciencias de la Computación,lucho,báez llorente,lbáez@@yahoo.com,La Serena,lbáez,Masculino,139925222,Araucanía,-,-,-,-,81,-,81,1617153755
133,Academia Chilena de Ciencias Sociales,Educación y Pedagogía,Adolfo,Garcia Codina,agarcia@gmail.com,Santiago,agarcia,Femenino,218.537.216,Región Metropolitana,96,-,52,-,-,-,74,1658614458
134,Centro de Estudios Patagónicos,Administración Pública,Pili,Coloma Benet,pcoloma@gmail.com,Puerto Montt,pcoloma,Femenino,24.054.471-7,Los Lagos,-,-,59,-,-,-,59,1603077812

Duplicados por 'RUT': 15

,RUT,Nombre,Apellido(s),Institución
113,10.438.826-0,MARIANA,Valverde Bru,Universidad del Pacífico
130,10.438.826-0,MARIANA,Valverde Bru,Universidad del Pacífico
129,11.831.944-8,Florencio,Losada Julián,Instituto Tecnológico Andino
49,11.831.944-8,Florencio,Losada Julián,Instituto Tecnológico Andino
123,120427332,Remigio,Amorós Llopis,Centro de Estudios Patagónicos
87,120427332,Remigio,Amorós Llopis,Centro de Estudios Patagónicos
126,12186570,Amaya,Escribano Espada,Centro de Estudios Patagónicos
101,12186570,Amaya,Escribano Espada,Centro de Estudios Patagónicos
105,13890179,melchor,alsina borja,Centro de Estudios Patagónicos
128,13890179,melchor,alsina borja,Centro de Estudios Patagónicos
41,139925222,lucho,báez llorente,Escuela Nacional de Ingeniería
132,139925222,lucho,báez llorente,Escuela Nacional de Ingeniería
125,17.508.442,griselda,vilanova tello,Centro de Estudios Patagónicos
13,17.508.442,griselda,vilanova tello,Centro de Estudios Patagónicos
74,18.066.935-3,azahara,arana amat,Universidad del Pacífico
121,18.066.935-3,azahara,arana amat,Universidad del Pacífico
112,18.816.991-4,ASUNCIÓN,Julián Torrent,Universidad del Pacífico
120,18.816.991-4,ASUNCIÓN,Julián Torrent,Universidad del Pacífico
97,205971883,CANDELARIA,Puga Nebot,Universidad del Pacífico
124,205971883,CANDELARIA,Puga Nebot,Universidad del Pacífico
94,218.537.216,Adolfo,Garcia Codina,Academia Chilena de Ciencias Sociales
133,218.537.216,Adolfo,Garcia Codina,Academia Chilena de Ciencias Sociales
122,218785978,Ernesto,Sabater Martorell,Centro de Estudios Patagónicos
79,218785978,Ernesto,Sabater Martorell,Centro de Estudios Patagónicos
5,22542550,feliciano,vallejo alemany,Instituto Tecnológico Andino
127,22542550,feliciano,vallejo alemany,Instituto Tecnológico Andino
22,24.054.471-7,Pili,Coloma Benet,Centro de Estudios Patagónicos
134,24.054.471-7,Pili,Coloma Benet,Centro de Estudios Patagónicos
62,24507554-5,JUAN,Jerez Cañellas,Centro de Estudios Patagónicos
131,24507554-5,JUAN,Jerez Cañellas,Centro de Estudios Patagónicos

Duplicados por 'Nombre de usuario': 15

,Nombre de usuario,Nombre,Apellido(s),Institución
74,aarana,azahara,arana amat,Universidad del Pacífico
121,aarana,azahara,arana amat,Universidad del Pacífico
126,aescribano,Amaya,Escribano Espada,Centro de Estudios Patagónicos
101,aescribano,Amaya,Escribano Espada,Centro de Estudios Patagónicos
94,agarcia,Adolfo,Garcia Codina,Academia Chilena de Ciencias Sociales
133,agarcia,Adolfo,Garcia Codina,Academia Chilena de Ciencias Sociales
120,ajulián,ASUNCIÓN,Julián Torrent,Universidad del Pacífico
112,ajulián,ASUNCIÓN,Julián Torrent,Universidad del Pacífico
124,cpuga,CANDELARIA,Puga Nebot,Universidad del Pacífico
97,cpuga,CANDELARIA,Puga Nebot,Universidad del Pacífico
122,esabater,Ernesto,Sabater Martorell,Centro de Estudios Patagónicos
79,esabater,Ernesto,Sabater Martorell,Centro de Estudios Patagónicos
129,flosada,Florencio,Losada Julián,Instituto Tecnológico Andino
49,flosada,Florencio,Losada Julián,Instituto Tecnológico Andino
127,fvallejo,feliciano,vallejo alemany,Instituto Tecnológico Andino
5,fvallejo,feliciano,vallejo alemany,Instituto Tecnológico Andino
125,gvilanova,griselda,vilanova tello,Centro de Estudios Patagónicos
13,gvilanova,griselda,vilanova tello,Centro de Estudios Patagónicos
131,jjerez,JUAN,Jerez Cañellas,Centro de Estudios Patagónicos
62,jjerez,JUAN,Jerez Cañellas,Centro de Estudios Patagónicos
41,lbáez,lucho,báez llorente,Escuela Nacional de Ingeniería
132,lbáez,lucho,báez llorente,Escuela Nacional de Ingeniería
128,malsina,melchor,alsina borja,Centro de Estudios Patagónicos
105,malsina,melchor,alsina borja,Centro de Estudios Patagónicos
130,mvalverde,MARIANA,Valverde Bru,Universidad del Pacífico
113,mvalverde,MARIANA,Valverde Bru,Universidad del Pacífico
22,pcoloma,Pili,Coloma Benet,Centro de Estudios Patagónicos
134,pcoloma,Pili,Coloma Benet,Centro de Estudios Patagónicos
87,ramorós,Remigio,Amorós Llopis,Centro de Estudios Patagónicos
123,ramorós,Remigio,Amorós Llopis,Centro de Estudios Patagónicos

Duplicados por 'Dirección de correo': 22

,Dirección de correo,Nombre,Apellido(s),Institución
121,aarana@gmail.com,azahara,arana amat,Universidad del Pacífico
74,aarana@gmail.com,azahara,arana amat,Universidad del Pacífico
101,aescribanogmail.com,Amaya,Escribano Espada,Centro de Estudios Patagónicos
126,aescribanogmail.com,Amaya,Escribano Espada,Centro de Estudios Patagónicos
133,agarcia@gmail.com,Adolfo,Garcia Codina,Academia Chilena de Ciencias Sociales
94,agarcia@gmail.com,Adolfo,Garcia Codina,Academia Chilena de Ciencias Sociales
112,ajulián@gmail.com,ASUNCIÓN,Julián Torrent,Universidad del Pacífico
120,ajulián@gmail.com,ASUNCIÓN,Julián Torrent,Universidad del Pacífico
86,correo_invalido,Francisco,Sierra Peñas,Academia Chilena de Ciencias Sociales
85,correo_invalido,Benigna,Cisneros Pallarès,Academia Chilena de Ciencias Sociales
84,correo_invalido,sosimo,pedrero quirós,Academia Chilena de Ciencias Sociales
116,correo_invalido,Adrián,Benet Aramburu,Universidad del Pacífico
35,correo_invalido,manolo,tamayo ayllón,Academia Chilena de Ciencias Sociales
20,correo_invalido,Alejandro,Quiroga Carrasco,Centro de Estudios Patagónicos
12,correo_invalido,Anunciación,Peña Rincón,Universidad del Pacífico
64,correo_invalido,nayara,domingo prieto,Escuela Nacional de Ingeniería
124,cpuga@@yahoo.com,CANDELARIA,Puga Nebot,Universidad del Pacífico
97,cpuga@@yahoo.com,CANDELARIA,Puga Nebot,Universidad del Pacífico
122,esabater@gmail.com,Ernesto,Sabater Martorell,Centro de Estudios Patagónicos
79,esabater@gmail.com,Ernesto,Sabater Martorell,Centro de Estudios Patagónicos
49,flosada@yahoo.com,Florencio,Losada Julián,Instituto Tecnológico Andino
129,flosada@yahoo.com,Florencio,Losada Julián,Instituto Tecnológico Andino
127,fvallejo@hotmail.com,feliciano,vallejo alemany,Instituto Tecnológico Andino
5,fvallejo@hotmail.com,feliciano,vallejo alemany,Instituto Tecnológico Andino
125,gvilanova,griselda,vilanova tello,Centro de Estudios Patagónicos
13,gvilanova,griselda,vilanova tello,Centro de Estudios Patagónicos
62,jjerez@gmail.com,JUAN,Jerez Cañellas,Centro de Estudios Patagónicos
131,jjerez@gmail.com,JUAN,Jerez Cañellas,Centro de Estudios Patagónicos
41,lbáez@@yahoo.com,lucho,báez llorente,Escuela Nacional de Ingeniería
132,lbáez@@yahoo.com,lucho,báez llorente,Escuela Nacional de Ingeniería
105,malsina@yahoo.com,melchor,alsina borja,Centro de Estudios Patagónicos
128,malsina@yahoo.com,melchor,alsina borja,Centro de Estudios Patagónicos
130,mvalverde,MARIANA,Valverde Bru,Universidad del Pacífico
113,mvalverde,MARIANA,Valverde Bru,Universidad del Pacífico
22,pcoloma@gmail.com,Pili,Coloma Benet,Centro de Estudios Patagónicos
134,pcoloma@gmail.com,Pili,Coloma Benet,Centro de Estudios Patagónicos
87,ramorós@gmail.com,Remigio,Amorós Llopis,Centro de Estudios Patagónicos
123,ramorós@gmail.com,Remigio,Amorós Llopis,Centro de Estudios Patagónicos