In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset_tiempo_entrega.csv")

In [3]:
df.columns

Index(['zona', 'tiempo_entrega_horas'], dtype='object')

In [4]:
df.head(10)

     zona  tiempo_entrega_horas
0  Centro                  39.0
1  Centro                  35.2
2   Norte                  39.9
3   Norte                  45.1
4   Norte                  34.6
5     Sur                  34.6
6  Centro                  45.5
7     Sur                  40.6
8   Norte                  33.2
9  Centro                  39.3

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   zona                  205 non-null    object
 1   tiempo_entrega_horas  205 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.3+ KB

In [6]:
#Valores nulos
print(df.isnull().sum())

zona                    0
tiempo_entrega_horas    0
dtype: int64

In [7]:
df["tiempo_entrega_horas"] = pd.to_numeric(df["tiempo_entrega_horas"], errors="coerce")

In [8]:
df

       zona  tiempo_entrega_horas
0    Centro                  39.0
1    Centro                  35.2
2     Norte                  39.9
3     Norte                  45.1
4     Norte                  34.6
..      ...                   ...
200  Centro                  80.0
201   Norte                  90.0
202   Norte                 120.0
203  Centro                 150.0
204   Norte                 200.0

[205 rows x 2 columns]

In [9]:
media = df["tiempo_entrega_horas"].mean()
print("La media de tiempos de entrega en horas es de ", media)

La media de tiempos de entrega en horas es de  38.00536585365854

In [10]:
mediana = df["tiempo_entrega_horas"].median()
print("La mediana de tiempos de entrega es: ", mediana)

La mediana de tiempos de entrega es:  36.3

In [11]:
moda = df["tiempo_entrega_horas"].mode()
print("La moda es: ", moda)

La moda es:  0    40.9
Name: tiempo_entrega_horas, dtype: float64

Medidas de dispersión

In [12]:
varianza = df["tiempo_entrega_horas"].var()
varianza

280.3576671449067

In [13]:
desv_std = df["tiempo_entrega_horas"].std()
desv_std

16.74388447000596

In [ ]:
moda = df["tiempo_entrega_horas"].mode()
moda

0    40.9
Name: tiempo_entrega_horas, dtype: float64

In [14]:
coef_var = (desv_std / media ) * 100
coef_var

np.float64(44.05663277780059)

In [15]:
df["tiempo_entrega_horas"].describe()

count    205.000000
mean      38.005366
std       16.743884
min       20.300000
25%       31.900000
50%       36.300000
75%       39.500000
max      200.000000
Name: tiempo_entrega_horas, dtype: float64

In [16]:
resumen_zona = df.groupby("zona")["tiempo_entrega_horas"].agg(
    media="mean",
    mediana = "median",
    varianza = "var",
    desv_std = "std",
    minimo = "min",
    maximo = "max",
    conteo = "count"
)

In [17]:
resumen_zona

            media  mediana    varianza   desv_std  minimo  maximo  conteo
zona
Centro  37.516667     35.7  233.066479  15.266515    24.1   150.0      72
Norte   39.871429     36.5  504.297068  22.456560    24.5   200.0      77
Sur     36.067857     36.6   33.147675   5.757402    20.3    49.1      56

In [18]:
resumen_zona["coef_variacon_%"] = (
    resumen_zona["desv_std"] / resumen_zona["media"]
) * 100

In [19]:
resumen_zona

,media,mediana,varianza,desv_std,minimo,maximo,conteo,coef_variacon_%
zona,,,,,,,,
Centro,37.516667,35.7,233.066479,15.266515,24.1,150.0,72,40.692621
Norte,39.871429,36.5,504.297068,22.456560,24.5,200.0,77,56.322435
Sur,36.067857,36.6,33.147675,5.757402,20.3,49.1,56,15.962694

In [20]:
resumen_zona.sort_values(by="media", ascending=False)

,media,mediana,varianza,desv_std,minimo,maximo,conteo,coef_variacon_%
zona,,,,,,,,
Norte,39.871429,36.5,504.297068,22.456560,24.5,200.0,77,56.322435
Centro,37.516667,35.7,233.066479,15.266515,24.1,150.0,72,40.692621
Sur,36.067857,36.6,33.147675,5.757402,20.3,49.1,56,15.962694

In [21]:
print(f"El tiempo promedio general de entregas es de {media:.2f} horas.")
print(f"La mediana es de {mediana:.2f} horas.")

El tiempo promedio general de entregas es de 38.01 horas.
La mediana es de 36.30 horas.

In [22]:
if media > mediana:
    print("La media es mayor que la mediana, lo que puede sugerir valores extremos altos")
elif media < mediana:
    print("La meddia es menor que la mediana, lo que puede sugerir valores extremos bajos")
else:
    print("La media y la mediana son muy similares")

La media es mayor que la mediana, lo que puede sugerir valores extremos altos

In [23]:
zona_mayor_media = resumen_zona["media"].idxmax()
zona_mayor_media

'Norte'

In [24]:
zona_mayor_cv = resumen_zona["coef_variacon_%"].idxmax()
zona_mayor_cv

'Norte'

In [25]:
print(f"La zona con mayor tiempo promedio es {zona_mayor_media}")

La zona con mayor tiempo promedio es Norte

In [26]:
print(f"La zona con mayor variabilidad relativa es {zona_mayor_cv}")

La zona con mayor variabilidad relativa es Norte

In [28]:
df.describe()

       tiempo_entrega_horas
count            205.000000
mean              38.005366
std               16.743884
min               20.300000
25%               31.900000
50%               36.300000
75%               39.500000
max              200.000000